apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp_v6.fullname" . }}-billing
spec:
  selector:
    {{- include "myapp_v6.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.billingAppPort }}
      targetPort: billing-web
