kind: ConfigMap
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "myapp.fullname" . }}-notification-php-config
data:
  DATABASE_HOST: {{ .Values.mysql.fullnameOverride | quote }}
  DATABASE_PORT: {{ .Values.mysql.service.port | quote }}
  DATABASE_NAME: {{ .Values.mysql.mysqlDatabase | quote }}
  CLIENT_SERVICE_HOST: {{ include "myapp.fullname" . }}-client:{{ .Values.service.clientAppPort }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "myapp.fullname" . }}-notification-php-secret
type: Opaque
data:
  DATABASE_USERNAME: {{ .Values.mysql.mysqlUser | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.mysql.mysqlPassword | b64enc | quote }}
