apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp_v4.fullname" . }}-panel
  labels:
    app: {{ include "myapp_v4.fullname" . }}-app-panel
spec:
  replicas: {{ .Values.userPanelReplicaCount }}
  selector:
     matchLabels:
       app: {{ include "myapp_v4.fullname" . }}-app-panel
  template:
     metadata:
        labels:
          app: {{ include "myapp_v4.fullname" . }}-app-panel
     spec:
        volumes:
          - name: {{ include "myapp_v4.fullname" . }}-shared-files-panel
            emptyDir: {}

          - name: {{ include "myapp_v4.fullname" . }}-nginx-config-volume-panel
            configMap:
              name: {{ include "myapp_v4.fullname" . }}-nginx-config

        containers:
          - image: {{ .Values.image.userPanel }}
            name: {{ include "myapp_v4.fullname" . }}-app-panel
            env:
              - name: USER_API_SERVICE_URL
                value: "http://{{ include "myapp_v4.fullname" . }}:{{ .Values.service.userApiPort }}"
              - name: BASE_URL
                value: {{ .Values.ingress.path }}
            volumeMounts:
              - name: {{ include "myapp_v4.fullname" . }}-shared-files-panel
                mountPath: /var/www/html
            lifecycle:
              postStart:
                exec:
                  command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html"]

          - image: nginx:1.7.9
            name: {{ include "myapp_v4.fullname" . }}-nginx-panel
            ports:
                - name: web-panel
                  containerPort: 80
            volumeMounts:
              - name: {{ include "myapp_v4.fullname" . }}-shared-files-panel
                mountPath: /var/www/html
              - name: {{ include "myapp_v4.fullname" . }}-nginx-config-volume-panel
                mountPath: /etc/nginx/conf.d/default.conf
                subPath: default.conf
