{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
  {{- else -}}
apiVersion: extensions/v1beta1
  {{- end }}
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "myapp.fullname" . }}-ingress-auth
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  rules:
    - host:  {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.authServicePath }}($|/)(.*)
            backend:
              serviceName: {{ include "myapp.fullname" . }}-auth
              servicePort: {{ .Values.service.authAppPort }}

          - path: {{ .Values.ingress.clientOrchestratorPath }}($|/)(.*)
            backend:
              serviceName: {{ include "myapp.fullname" . }}-clientorch
              servicePort: {{ .Values.service.clientOrchestratorPort }}
