{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
  {{- else -}}
apiVersion: extensions/v1beta1
  {{- end }}
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "myapp.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  rules:
    - host:  {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.authServicePath }}($|/)(.*)
            backend:
              serviceName: {{ include "myapp.fullname" . }}-auth
              servicePort: {{ .Values.service.authAppPort }}

          - path: {{ .Values.ingress.clientServicePath }}($|/)(.*)
            backend:
              serviceName: {{ include "myapp.fullname" . }}-auth
              servicePort: {{ .Values.service.clientAppPort }}

          - path: {{ .Values.ingress.notificationServicePath }}($|/)(.*)
            backend:
              serviceName: {{ include "myapp.fullname" . }}-notification
              servicePort: {{ .Values.service.notificationAppPort }}

          - path: {{ .Values.ingress.orderServicePath }}($|/)(.*)
            backend:
              serviceName: {{ include "myapp.fullname" . }}-order
              servicePort: {{ .Values.service.orderAppPort }}

          - path: {{ .Values.ingress.billingServicePath }}($|/)(.*)
            backend:
              serviceName: {{ include "myapp.fullname" . }}-billing
              servicePort: {{ .Values.service.billingAppPort }}

          - path: {{ .Values.ingress.clientOrchestratorPath }}($|/)(.*)
            backend:
              serviceName: {{ include "myapp.fullname" . }}-clientorch
              servicePort: {{ .Values.service.clientOrchestratorPort }}

          - path: {{ .Values.ingress.orderOrchestratorPath }}($|/)(.*)
            backend:
              serviceName: {{ include "myapp.fullname" . }}-orderorch
              servicePort: {{ .Values.service.orderOrchestratorPort }}