apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "myapp.fullname" . }}-order
spec:
  selector:
    {{- include "myapp.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.orderAppPort }}
      targetPort: order-web
