kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "myapp_v6.fullname" . }}-notification-php-config
data:
  DATABASE_HOST: {{ .Values.mysql.fullnameOverride | quote }}
  DATABASE_PORT: {{ .Values.mysql.service.port | quote }}
  DATABASE_NAME: {{ .Values.mysql.mysqlDatabase | quote }}
  USER_SERVICE_HOST: {{ include "myapp_v6.fullname" . }}-user:{{ .Values.service.userAppPort }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myapp_v6.fullname" . }}-notification-php-secret
type: Opaque
data:
  DATABASE_USERNAME: {{ .Values.mysql.mysqlUser | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.mysql.mysqlPassword | b64enc | quote }}
