apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "myapp.fullname" . }}-orderorchestrator
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
     matchLabels:
        {{- include "myapp.selectorLabels" . | nindent 8 }}
  template:
     metadata:
        labels:
          {{- include "myapp.selectorLabels" . | nindent 10 }}
     spec:
        volumes:
          - name: {{ include "myapp.fullname" . }}-orderorchestrator-shared-files
            emptyDir: {}

          - name: {{ include "myapp.fullname" . }}-orderorchestrator-nginx-config-volume
            configMap:
              name: {{ include "myapp.fullname" . }}-orderorchestrator-nginx-config

        containers:
          - image: {{ .Values.image.orderOrchestratorRepository }}
            name: {{ include "myapp.fullname" . }}-orderorchestrator-app
            env:
              - name: ORDER_SERVICE_HOST
                valueFrom:
                  configMapKeyRef:
                    name: {{ include "myapp.fullname" . }}-orderorchestrator-php-config
                    key: ORDER_SERVICE_HOST
              - name: BILLING_SERVICE_HOST
                valueFrom:
                  configMapKeyRef:
                    name: {{ include "myapp.fullname" . }}-orderorchestrator-php-config
                    key: BILLING_SERVICE_HOST
              - name: NOTIFICATION_SERVICE_HOST
                valueFrom:
                  configMapKeyRef:
                    name: {{ include "myapp.fullname" . }}-orderorchestrator-php-config
                    key: NOTIFICATION_SERVICE_HOST
              - name: DATABASE_HOST
                valueFrom:
                  configMapKeyRef:
                    name: {{ include "myapp.fullname" . }}-orderorchestrator-php-config
                    key: DATABASE_HOST
              - name: DATABASE_PORT
                valueFrom:
                  configMapKeyRef:
                    name: {{ include "myapp.fullname" . }}-orderorchestrator-php-config
                    key: DATABASE_PORT
              - name: DATABASE_NAME
                valueFrom:
                  configMapKeyRef:
                    name: {{ include "myapp.fullname" . }}-orderorchestrator-php-config
                    key: DATABASE_NAME
              - name: DATABASE_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: {{ include "myapp.fullname" . }}-orderorchestrator-php-secret
                    key: DATABASE_USERNAME
              - name: DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ include "myapp.fullname" . }}-orderorchestrator-php-secret
                    key: DATABASE_PASSWORD
            volumeMounts:
              - name: {{ include "myapp.fullname" . }}-orderorchestrator-shared-files
                mountPath: /var/www/html
            lifecycle:
              postStart:
                exec:
                  command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html"]

          - image: nginx:1.7.9
            name: {{ include "myapp.fullname" . }}-orderorchestrator-nginx
            ports:
              - name: orderorch-web
                containerPort: 80
            volumeMounts:
              - name: {{ include "myapp.fullname" . }}-orderorchestrator-shared-files
                mountPath: /var/www/html
              - name: {{ include "myapp.fullname" . }}-orderorchestrator-nginx-config-volume
                mountPath: /etc/nginx/conf.d/default.conf
                subPath: default.conf
            livenessProbe:
                httpGet:
                  port: 80
                  path: /
                initialDelaySeconds: 10
                periodSeconds: 5
                timeoutSeconds: 2
            readinessProbe:
                httpGet:
                  port: 80
                  path: /health
                initialDelaySeconds: 10
                periodSeconds: 5
