apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp_v5.fullname" . }}-app
  labels:
    {{- include "myapp_v5.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
     matchLabels:
        {{- include "myapp_v5.selectorLabels" . | nindent 8 }}
  template:
     metadata:
        labels:
          {{- include "myapp_v5.selectorLabels" . | nindent 10 }}
     spec:
        volumes:
          - name: {{ include "myapp_v5.fullname" . }}-app-shared-files
            emptyDir: {}

          - name: {{ include "myapp_v5.fullname" . }}-app-nginx-config-volume
            configMap:
              name: {{ include "myapp_v5.fullname" . }}-app-nginx-config

        containers:
          - image: {{ .Values.image.testAppRepository }}
            name: {{ include "myapp_v5.fullname" . }}-app-app
            volumeMounts:
              - name: {{ include "myapp_v5.fullname" . }}-app-shared-files
                mountPath: /var/www/html
            lifecycle:
              postStart:
                exec:
                  command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html"]

          - image: nginx:1.7.9
            name: {{ include "myapp_v5.fullname" . }}-app-nginx
            ports:
              - name: app-web
                containerPort: 80
            volumeMounts:
              - name: {{ include "myapp_v5.fullname" . }}-app-shared-files
                mountPath: /var/www/html
              - name: {{ include "myapp_v5.fullname" . }}-app-nginx-config-volume
                mountPath: /etc/nginx/conf.d/default.conf
                subPath: default.conf
#            livenessProbe:
#                httpGet:
#                  port: 80
#                  path: /
#                initialDelaySeconds: 10
#                periodSeconds: 5
#                timeoutSeconds: 2
#            readinessProbe:
#                httpGet:
#                  port: 80
#                  path: /health
#                initialDelaySeconds: 10
#                periodSeconds: 5
