apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp_v5.fullname" . }}-auth
spec:
  selector:
    {{- include "myapp_v5.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.authAppPort }}
      targetPort: auth-web
